server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/proyectoBack
      
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
      
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
queue:
  movie:
    name: movieQueue

eureka:
  client:
    service-url:
      default-zone: http:/localhost:8761/eureka/
